### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by F4nX1ngCN** [Neoministein/Interstellar.BanSystem#1]
i used it on my client and server but therers no ui on my client :(

**Comment by Neoministein** [comment]
Hey, thanks for taking interest in the mod. 

However I would need some more information so I can help you.

1. What version of Northstar are you using?
2. Do you see the mod in the in mod overview in the main menu?
3. Where are you looking for the UI?
The UI is located under Private Match > Settings >Banned Equipment

**Comment by F4nX1ngCN** [comment]
i found where the problem it is, im still finding the ui in main menu, anyway thx for your coding.
